#!/usr/bin/env tsx
/**
 * Regenerates tools/posthog/types/posthog-api.gen.ts from PostHog's published
 * OpenAPI spec. Run quarterly or whenever PostHog changes their API surface.
 *
 * Usage: nx run posthog-tools:generate-types
 */
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';

const POSTHOG_SCHEMA_URL = 'https://us.posthog.com/api/schema/';
const OUTPUT_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'types',
  'posthog-api.gen.ts',
);

async function main(): Promise<void> {
  console.log(`Fetching OpenAPI spec from ${POSTHOG_SCHEMA_URL}...`);
  const ast = await openapiTS(new URL(POSTHOG_SCHEMA_URL));
  const contents = astToString(ast);
  const header = `/* eslint-disable */\n// Generated by tools/posthog/scripts/generate-types.ts.\n// DO NOT EDIT MANUALLY. Run: npx nx run posthog-tools:generate-types\n// Source: ${POSTHOG_SCHEMA_URL}\n\n`;
  await writeFile(OUTPUT_PATH, header + contents, 'utf8');
  console.log(`Wrote ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
