const BARS = ['▁', '▂', '▃', '▄', '▅', '▆', '▇', '█'];

export function sparkline(values: readonly number[]): string {
  if (values.length === 0) return '—';
  const max = Math.max(...values, 1);
  return values
    .map((v) => BARS[Math.min(7, Math.round((v / max) * 7))])
    .join('');
}

export function formatDeltaCell({ thisWeek, lastWeek }: { thisWeek: number; lastWeek: number }): string {
  const diff = thisWeek - lastWeek;
  const sign = diff >= 0 ? '+' : '';
  if (lastWeek === 0) {
    return diff > 0 ? `${sign}${diff} (new)` : '—';
  }
  const pct = Math.round(((thisWeek - lastWeek) / lastWeek) * 100);
  const pctSign = pct >= 0 ? '+' : '';
  return `${sign}${diff} (${pctSign}${pct}%)`;
}

export interface ReportRow {
  metric: string;
  thisWeek: number;
  lastWeek: number;
  weeks: readonly number[];  // 4 most recent buckets
}

export interface ReportSection {
  name: string;
  rows: ReportRow[];
}

export function renderReport(sections: ReportSection[], date: string): string {
  const lines: string[] = [];
  lines.push(`# GTM weekly snapshot — ${date}`);
  lines.push('');
  lines.push('> Generated by `nx run posthog-tools:report`. Notes below are hand-edited.');
  lines.push('');
  for (const section of sections) {
    lines.push(`## ${section.name}`);
    lines.push('');
    lines.push('| Metric | This week | Last week | Δ | 4-wk |');
    lines.push('|--------|----------:|----------:|--:|------|');
    for (const row of section.rows) {
      lines.push(
        `| ${row.metric} | ${row.thisWeek.toLocaleString()} | ${row.lastWeek.toLocaleString()} | ${formatDeltaCell({ thisWeek: row.thisWeek, lastWeek: row.lastWeek })} | ${sparkline(row.weeks)} |`,
      );
    }
    lines.push('');
  }
  lines.push('## Notes');
  lines.push('');
  lines.push('<!-- HUMAN: edit this section before merging the PR. Three bullets max. -->');
  lines.push('- _Add observations here before merging._');
  lines.push('');
  return lines.join('\n');
}

import { writeFile, mkdir, access } from 'node:fs/promises';
import { join, resolve as resolvePath, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ph } from './client.js';

interface FetchedInsight {
  id: number;
  name: string;
  filters?: { insight?: string };
  result?: any;
}

interface FetchedDashboard {
  id: number;
  name: string;
  tags?: string[];
  tiles?: Array<{ insight?: number | { id: number } }>;
}

function extractWeeklyValues(insight: FetchedInsight): { thisWeek: number; lastWeek: number; weeks: number[] } {
  // PostHog trends return result[0].data as an array of daily counts.
  // We fold into 7-day buckets, newest first.
  const series = (Array.isArray(insight.result) ? insight.result[0]?.data : insight.result?.[0]?.data) ?? [];
  const buckets: number[] = [];
  for (let i = 0; i < 4; i++) {
    const start = series.length - (i + 1) * 7;
    const end = series.length - i * 7;
    if (start < 0) break;
    buckets.unshift(series.slice(start, end).reduce((a: number, b: number) => a + b, 0));
  }
  while (buckets.length < 4) buckets.unshift(0);
  return {
    thisWeek: buckets[buckets.length - 1] ?? 0,
    lastWeek: buckets[buckets.length - 2] ?? 0,
    weeks: buckets,
  };
}

// Throws on PostHog HTTP errors instead of silently returning empty results.
// A zero-row report is signal; a failed-auth empty report is misleading.
function expectOk<T>(r: { data?: T; error?: unknown }, op: string): T {
  if (r.error || r.data === undefined) {
    throw new Error(`PostHog ${op} failed: ${JSON.stringify(r.error)}`);
  }
  return r.data;
}

export async function generateReport(): Promise<{ markdown: string; date: string }> {
  const c = ph();
  const dashRes = await c.GET('/dashboards/' as any, { params: { query: { limit: 200 } } } as any);
  const dashData = expectOk(dashRes as any, 'list dashboards') as { results?: FetchedDashboard[] };
  const dashboards = dashData.results ?? [];
  const gtmDashboards = dashboards.filter((d) => d.tags?.includes('gtm'));

  const sections: ReportSection[] = [];
  for (const d of gtmDashboards) {
    const rows: ReportRow[] = [];
    for (const tile of d.tiles ?? []) {
      const tileId = typeof tile.insight === 'number' ? tile.insight : tile.insight?.id;
      if (typeof tileId !== 'number') continue;
      const insightRes = await c.GET(`/insights/{id}/` as any, {
        params: { path: { id: tileId }, query: { refresh: 'force_cache' } },
      } as any);
      const insight = expectOk(insightRes as any, `get insight ${tileId}`) as FetchedInsight;
      const { thisWeek, lastWeek, weeks } = extractWeeklyValues(insight);
      rows.push({ metric: insight.name, thisWeek, lastWeek, weeks });
    }
    sections.push({ name: d.name, rows });
  }

  const date = new Date().toISOString().slice(0, 10);
  return { markdown: renderReport(sections, date), date };
}

async function nextOutputPath(reportsDir: string, date: string): Promise<string> {
  const base = join(reportsDir, `${date}-weekly`);
  let candidate = `${base}.md`;
  let suffix = 2;
  while (true) {
    try {
      await access(candidate);
      candidate = `${base}-${suffix}.md`;
      suffix += 1;
    } catch {
      return candidate;
    }
  }
}

async function main(): Promise<number> {
  let report: { markdown: string; date: string };
  try {
    report = await generateReport();
  } catch (err) {
    console.error(`Report generation failed: ${err instanceof Error ? err.message : err}`);
    return 1;
  }
  const here = dirname(fileURLToPath(import.meta.url));
  const reportsDir = resolvePath(here, '..', '..', 'docs', 'gtm', 'reports');
  await mkdir(reportsDir, { recursive: true });
  const outPath = await nextOutputPath(reportsDir, report.date);
  await writeFile(outPath, report.markdown, 'utf8');
  console.log(`Wrote ${outPath}`);
  return 0;
}

const isDirectRun = process.argv[1] && resolvePath(process.argv[1]) === fileURLToPath(import.meta.url);
if (isDirectRun) {
  main().then((code) => process.exit(code));
}
