const BARS = ['▁', '▂', '▃', '▄', '▅', '▆', '▇', '█'];

export function sparkline(values: readonly number[]): string {
  if (values.length === 0) return '—';
  const max = Math.max(...values, 1);
  return values
    .map((v) => BARS[Math.min(7, Math.round((v / max) * 7))])
    .join('');
}

export function formatDeltaCell({ thisWeek, lastWeek }: { thisWeek: number; lastWeek: number }): string {
  const diff = thisWeek - lastWeek;
  const sign = diff >= 0 ? '+' : '';
  if (lastWeek === 0) {
    return diff > 0 ? `${sign}${diff} (new)` : '—';
  }
  const pct = Math.round(((thisWeek - lastWeek) / lastWeek) * 100);
  const pctSign = pct >= 0 ? '+' : '';
  return `${sign}${diff} (${pctSign}${pct}%)`;
}

export interface ReportRow {
  metric: string;
  thisWeek: number;
  lastWeek: number;
  weeks: readonly number[];  // 4 most recent buckets
}

export interface ReportSection {
  name: string;
  rows: ReportRow[];
}

export function renderReport(sections: ReportSection[], date: string): string {
  const lines: string[] = [];
  lines.push(`# GTM weekly snapshot — ${date}`);
  lines.push('');
  lines.push('> Generated by `nx run posthog-tools:report`. Notes below are hand-edited.');
  lines.push('');
  for (const section of sections) {
    lines.push(`## ${section.name}`);
    lines.push('');
    lines.push('| Metric | This week | Last week | Δ | 4-wk |');
    lines.push('|--------|----------:|----------:|--:|------|');
    for (const row of section.rows) {
      lines.push(
        `| ${row.metric} | ${row.thisWeek.toLocaleString()} | ${row.lastWeek.toLocaleString()} | ${formatDeltaCell({ thisWeek: row.thisWeek, lastWeek: row.lastWeek })} | ${sparkline(row.weeks)} |`,
      );
    }
    lines.push('');
  }
  lines.push('## Notes');
  lines.push('');
  lines.push('<!-- HUMAN: edit this section before merging the PR. Three bullets max. -->');
  lines.push('- _Add observations here before merging._');
  lines.push('');
  return lines.join('\n');
}
