name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.3.0
        with:
          node-version: 22
          cache: npm
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npx nx test mcp --skip-nx-cache
      - run: npx nx test angular
      - run: npx nx build angular --configuration=production
      - name: Publish to npm
        run: npx nx-release-publish angular
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
